export const USER = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
}

export const MEMORIES = {
  GET_LIST_MEMORIES_REQUEST: "GET_LIST_MEMORIES_REQUEST",
  GET_LIST_MEMORIES_SUCCESS: "GET_LIST_MEMORIES_SUCCESS",
  GET_LIST_MEMORIES_FAILURE: "GET_LIST_MEMORIES_FAILURE",
  CREATE_NEW_MEMORIES_REQUEST: "CREATE_NEW_MEMORIES_REQUEST",
  CREATE_NEW_MEMORIES_SUCCESS: "CREATE_NEW_MEMORIES_SUCCESS",
  CREATE_NEW_MEMORIES_FAILURE: "CREATE_NEW_MEMORIES_FAILURE",
}